<?php

function vendors_permission() {
    return array(
        'access module vendors' => array(
            'title' => t('管理供应商'),
        )
    );
}

function vendors_menu() {
    $items['vendors'] = array(
        'title' => '供应商列表',
        'description' => '供应商列表',
        'page callback' => '_vendors_list',
        'access arguments' => array('access module vendors'),
    );
    $items['vendors/orders/%order'] = array(
        'title' => '查看订单',
        'description' => '查看订单',
        'page callback' => '_order_render',
        'page arguments' => array(2),
        'access arguments' => array('access module vendors'),
        'file' => 'vendors_view_order.inc',
    );
    $items['vendors/orders/%order/edit'] = array(
        'title' => '编辑订单',
        'description' => '编辑订单',
        'page callback' => '_edit_order',
        'page arguments' => array(2),
        'access arguments' => array('access module vendors'),
        'file' => 'vendors_order.inc',
    );
    $items['vendors/orders/%order/delete'] = array(
        'title' => '删除订单',
        'description' => '删除订单',
        'page callback' => '_order_delete',
        'page arguments' => array(2),
        'access arguments' => array('access module vendors'),
        'file' => 'vendors_edit_order.inc',
    );
    $items['vendors/orders/%order/excel'] = array(
        'title' => '导出电子表格',
        'description' => '导出电子表格',
        'page callback' => 'order_to_excel',
        'page arguments' => array(2),
        'access arguments' => array('access module vendors'),
        'file' => 'vendors_excel.inc',
    );
    $items['vendors/add'] = array(
        'title' => '添加供应商',
        'description' => '添加一个供应商',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('_vendors_add_form'),
        'access arguments' => array('access module vendors'),
    );
    $items['vendors/%vendor'] = array(
        'title' => '查看供应商',
        'description' => '查看供应商',
        'page callback' => '_vendors_view',
        'page arguments' => array(1),
        'access arguments' => array('access module vendors'),
    );
    $items['vendors/%vendor/edit'] = array(
        'title' => '编辑供应商',
        'description' => '编辑供应商',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('_vendors_edit_form', 1),
        'access arguments' => array('access module vendors'),
    );
    $items['vendors/%vendor/products'] = array(
        'title' => '产品列表',
        'description' => '产品列表',
        'page callback' => '_vendor_products_render',
        'page arguments' => array(1),
        'access arguments' => array('access module vendors'),
        'file' => 'vendor_products.inc',
    );
    $items['vendors/%vendor/products/edit'] = array(
        'title' => '产品列表',
        'description' => '产品列表',
        'page callback' => '_vendor_products_edit',
        'page arguments' => array(1),
        'access arguments' => array('access module vendors'),
        'file' => 'vendor_products.inc',
    );
    $items['vendors/%vendor/add_order'] = array(
        'title' => '添加订单',
        'description' => '添加订单',
        'page callback' => '_add_order',
        'page arguments' => array(1),
        'access arguments' => array('access module vendors'),
        'file' => 'vendors_order.inc',
    );
    return $items;
}

function vendor_load($id) {
    $result = db_query('select * from {e_vendors} where vendor_id = :vendor_id limit 1', array(':vendor_id' => $id));
    if ($result->rowCount() != 0) {
        return $result->fetch();
    }
    return null;
}

function order_load($id) {
    $result = db_query('select * from {e_vendors_orders} where order_id = :order_id limit 1', array(':order_id' => $id));
    if ($result->rowCount() != 0) {
        return $result->fetch();
    }
    return null;
}

function _vendors_list() {
    $result = db_query('select * from {e_vendors}');
    $items = array();
    foreach ($result as $record) {
        $items[] = array(
            'data' => l($record->name, 'vendors/' . $record->vendor_id),
        );
    }
    if (count($items) == 0)
        return '供应商列表为空';
    else
        return theme('item_list', array('items' => $items));
}

function _vendors_add_form($form, &$form_state, $vendor = null) {
    if ($vendor == null) {
        $name = "";
        $tel = "";
        $fax = "";
        $address = "";
        $vendor_id = null;
    } else {
        $name = $vendor->name;
        $tel = $vendor->tel;
        $fax = $vendor->fax;
        $address = $vendor->address;
        $vendor_id = $vendor->vendor_id;
    }
    $form['vendor_id'] = array(
        '#type' => 'textfield',
        '#attributes' => array('style' => "display:none"),
        '#title' => t('ID'),
        '#default_value' => $vendor_id,
    );
    $form['description'] = array(
        '#type' => 'item',
            #'#title' => t('公司基本信息设置'),
    );
    $form['name'] = array(
        '#type' => 'textfield',
        '#title' => t('公司名'),
        '#default_value' => $name,
    );
    $form['tel'] = array(
        '#type' => 'textfield',
        '#title' => t('电话号码'),
        '#default_value' => $tel,
    );
    $form['fax'] = array(
        '#type' => 'textfield',
        '#title' => t('传真号码'),
        '#default_value' => $fax,
    );
    $form['address'] = array(
        '#type' => 'textfield',
        '#title' => t('地址'),
        '#default_value' => $address,
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => t('提交'),
    );
    return $form;
}

function _vendors_add_form_submit($form, &$form_state) {
    db_query('INSERT INTO e_vendors (name,tel,fax,address)VALUES (:name, :tel , :fax, :address)', array(
        ':name' => $form_state['values']['name'],
        ':tel' => $form_state['values']['tel'],
        ':fax' => $form_state['values']['fax'],
        ':address' => $form_state['values']['address'],
            )
    );
    drupal_set_message('提交成功');
    drupal_goto('/vendors');
}

function _vendors_add_form_validate($form, &$form_state) {
    if ($form_state['values']['name'] == '') {
        form_set_error('name', '公司名不能为空');
    }
}

function get_all_orders($vendor) {
    $result = db_query('select * from {e_vendors_orders} where vendor_id = :vendor_id', array(':vendor_id' => $vendor->vendor_id));
    $items = array();
    foreach ($result as $record) {
        $items[] = array(
            'data' => l($record->date, 'vendors/orders/' . $record->order_id),
        );
    }
    return theme('item_list', array('items' => $items));
}



function _vendors_view($vendor) {
    if ($vendor == null)
        return t('没有该供应商');
    $name = $vendor->name;
    $edit = l('编辑供应商的基本信息', 'vendors/' . $vendor->vendor_id . '/edit');
    $product = l('产品列表','vendors/' . $vendor->vendor_id . '/products');
    $orders = get_all_orders($vendor);
    $order = '订单列表<br/>' . l('添加订单', 'vendors/' . $vendor->vendor_id . '/add_order') . $orders;
    return $name . '<br/>' . $edit . '<br/>' . $product . '<br/>' . $order;
}

function _vendors_edit_form($form, &$form_state, $vendor) {
    return _vendors_add_form($form, $form_state, $vendor);
}

function _vendors_edit_form_validate($form, &$form_state) {
    if ($form_state['values']['name'] == '') {
        form_set_error('name', '公司名不能为空');
    }
}

function _vendors_edit_form_submit($form, &$form_state) {
    db_query('update e_vendors set name = :name, tel = :tel , fax = :fax, address = :address where vendor_id = :vendor_id', array(
        ':name' => $form_state['values']['name'],
        ':tel' => $form_state['values']['tel'],
        ':fax' => $form_state['values']['fax'],
        ':address' => $form_state['values']['address'],
        ':vendor_id' => $form_state['values']['vendor_id'],
            )
    );
    drupal_set_message('提交成功');
    drupal_goto('vendors/' . $form_state['values']['vendor_id']);
}
